### ISSUE TITLE
Add One-Roll Engine support

### ISSUE THREAD

**Issue by shemetz** [BernhardPosselt/foundryvtt-special-dice-roller#26]
I'm posting this as a suggestion, though I might go ahead and do it myself in the next few weeks/months if I have the time.  The docs make it seem very easy!

The One-Roll Engine, ORE, is pretty minimalist:

- players roll a number of dice, which are all d10s (dice with the values 1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
- for example, for 9d10 (or simply "9d"), a result could be `6, 3, 1, 8, 6, 8, 2, 6, 6`
- the players then succeed or fail based on the **sets** in the result.  each set consists of 2+ identical dice.
- each set's **width** is the amount of dice in the set, and its **height** is the face shared by these dice.  the width and height of a set are written shortly as WIDTHxHEIGHT.
- for example, for the above roll result, the sets are `4x6` and `2x8`.
- the users need to see the result of each d10 roll.  automatically identifying sets and outputting their width+height would be great.  visually marking the sets as part of the roll would be perfect - for example, by rendering the above roll as [**8 8** - **6 6 6 6** - 3 2 1]

**Comment by BernhardPosselt** [comment]
Wow, that seems incredibly complex. Given that you roll numerical dice I'd actually recommend that you go ahead and implement this in your own custom module. 

Here's the relevant roll API https://foundryvtt.com/api/Roll.html and a description how to write dice formulas https://foundryvtt.com/article/dice/ 

That way also Dice so Nice will work out of the box.

**Comment by BernhardPosselt** [comment]
BTW, let me know if you need help creating the module, I'm hanging out on the Foundry Discord #module-development

**Comment by shemetz** [comment]
Well, uh, I ended up adding it regardless 😅 

Only took a few hours - your codebase was really neat!

![image](https://user-images.githubusercontent.com/6516621/106324416-c5934b80-6281-11eb-849a-4f084f8514d8.png)

(images and formatting subject to change)

If you don't mind, I'll publish a pull request for it!

Also, @BernhardPosselt - are you `putty#0555` on Discord?  (I've seen absolutely no mention of this discord username in this github repository, I only found it by searching inside the server)

**Comment by BernhardPosselt** [comment]
Yep, putty. I'd really recommend to use the foundry roll API for that instead of my custom dice rolling implementation and create a separate module. It's super easy and should be doable in ~50 lines of JS in addition to your custom logic.

You really only need to implement the chatMessage hook here https://github.com/BernhardPosselt/foundryvtt-special-dice-roller/blob/master/src/index.ts#L75-L86 and return additional custom HTML (aka don't return false) that displays the result.

The benefit to doing it like that is you can use all the foundry built ins and modules that fire off of standard dice rolling. This module's main purpose is  dealing with custom dice that can't be rolled properly through Foundry's API at all, not implementing dice interpretation logic.

**Comment by shemetz** [comment]
Done!

https://github.com/itamarcu/one-roll-engine

(I also made a [fork of this system with the change](https://github.com/itamarcu/special-dice-roller), but I'll stop working on it)

**Comment by BernhardPosselt** [comment]
Well done! Looks as expected :)
